%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

SerialNumber: "00G88809809"
CameraName: "highres"
# Ros topic name
TopicName: "highres/image"
# Exposure Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
ExposureAuto: 0
AutoExposureTimeLower: 65
AutoExposureTimeUpper: 10000
# Gain Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
GainAuto: 0
ExposureTime: 15000
# Gamma Selector, 0 stands for user, 1 stands for sRGB
GammaSelector: 1

# Frame Rate (if trigger mode is on, frame rate is enable)
FrameRate: 30.0


